
# SEO settings
title: "Delapan Piksel"
title2: #"Piksel" # default: ""
description: "Sebuah website, berisi opini dari Jaka Santana"
keywords: "street photography, blog, fotografi, photography, personal, delapan piksel"
url: https://delapanpx.com # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: #UA-XXXXX-XX
disqus_shortname: # "hnbloggithub"
twitter_username: "delapanpx"
comments: false

# Build settings
permalink   : /:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jaka Santana"
  job      : "Visual Artist"
  bio      : "Saya itu doyan minum kopi murah, motret di jalanan, dan seorang Ayah"
  thumb    : /images/author.jpg
  email    : delapanpiksel@gmail.com
  url      : https://delapanpx.com
  github   : https://github.com/delapanpx
  twitter  : https://twitter.com/delapanpx
  facebook : https://www.facebook.com/delapanpiksel
  linkedin : #https://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@delapanpx"

plugins:
  - bourbon
  - jekyll-paginate

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock"]
include: ["robots.txt"]
